### ISSUE TITLE
SSE instead of WebSockets

### ISSUE THREAD

**Issue by radarsu** [apollographql/apollo-feature-requests#135]
- [x] feature

Http2 is coming, so SSE sounds to be better option for subscriptions handling than WebSockets. I come here with suggestion of replacing WS. Also, I was looking for some package to do this, but the only one I found was quite outdated.

**Comment by rmoutray-configureone** [comment]
Would love this feature even if only for the apollo-client.

**Comment by wmertens** [comment]
SSE is better than websockets:
- no extra port needed
- works with http2
- less resources
- very good browser support

The only disadvantage is that to send something to the browser, you have to go via HTTP instead of on an existing channel so you have a little more lag when sending. But with http2 that's not a problem.

**Comment by jerelmiller** [comment]
Hey all 👋 

There is now a community supported [graphql-sse](https://the-guild.dev/graphql/sse) implementation that you can use. You can find the recipe to work with Apollo here: https://the-guild.dev/graphql/sse/recipes#client-usage-with-apollo

Since this is a fairly well maintained community project, we are unlikely to put anything in core anytime soon. I'm going to close this issue for now. Feel free to open a new feature request if there is more you think we could be doing here. Thanks!
