### ISSUE TITLE
Federation: support custom directives in federated schemas

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/apollo-feature-requests#145]
In `@apollo/federation@0.6.0`, the [printSchema function](https://github.com/apollographql/apollo-server/blob/ce459ce979aacf8f3486804841127d7244646f03/packages/apollo-federation/src/service/printFederatedSchema.ts#L55) throws away SDL directives that aren't `@deprecated/@key/@external/@extends/@requires/@provides`.

This prevents the federation gateway from knowing about directives via the `_Service.sdl` field. 

Conveying custom directives from federated schemas to the gateway is the first step to supporting centralized logic in the gateway for functionality like unified authorization.

Thanks for the hard work!

**Comment by 3axap4eHko** [comment]
@trevor-scheer what if directives will be excluded only from `_Service.sdl` resolver but kept in introspection?

**Comment by pratiknikam** [comment]
We started implementing federation for our service and hit this exact roadblock.

**Comment by nazar** [comment]
Is there a rough ETA on when we could expect seeing custom directive support?

We are about to start a microservice oriented graphQL system and the lack of directive support is a roadblock for us, which is unfortunate as federated schemas tick so many boxes for us. 
 Having the [Schema stitching](https://www.apollographql.com/docs/graphql-tools/schema-stitching/) document marked as `deprecated` is also adding an element of uncertainty for us. 

Having a rough indication of when we could expect directive support - i.e. weeks or six months would greatly help in our architecture choices 🙏

**Comment by edelreal2** [comment]
Our use case for our current non-federated schema looks something like this:

```graphql
directive @authorize (
  requires: ResourcePrivilege = INTERNAL_OPERATIONS_PRIVILEGE,
) on OBJECT | FIELD_DEFINITION

type Query @authorize(requires: ACCOUNT_OPERATIONS_PRIVILEGE) {
  users: [User]
  customers: [Customer]
}

type Mutation @authorize(requires: ACCOUNT_OPERATIONS_PRIVILEGE) {
  addUserForCustomer(customerId: Int!, input: AddCustomerUserInput! ): AddCustomerUserResult

  deleteCustomer(customerId: Int! ): String @authorize(requires: SYSTEM_OPERATIONS_PRIVILEGE)
}
```

When attempting to convert our schema to a federated schema, I get an error like this one:

```shell
api_server/node_modules/graphql/validation/rules/KnownDirectives.js:86
        throw _iteratorError2;
        ^

TypeError: Cannot read property 'kind' of undefined
    at KnownDirectives (api_server/node_modules/graphql/validation/rules/KnownDirectives.js:70:15)
    at api_server/node_modules/graphql/validation/validate.js:63:12
    at Array.map (<anonymous>)
    at Object.validateSDL (api_server/node_modules/graphql/validation/validate.js:62:24)
    at Object.buildSchemaFromSDL (api_server/node_modules/apollo-graphql/src/schema/buildSchemaFromSDL.ts:69:18)
    at buildFederatedSchema (api_server/node_modules/@apollo/federation/src/service/buildFederatedSchema.ts:30:16)
    at Object.<anonymous> (api_server/api/sql/schema.external.js:47:40)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._compile (api_server/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (api_server/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

Since we use schema directives to implement access control, this is a roadblock for converting our current GraphQL service into a federated service.

**Comment by edelreal** [comment]
Our use case is to leverage directives for authorization. 

Our current non-federated `typeDefs` SDL looks something like this:

```graphql
directive @authorize (
  requires: ResourcePrivilege = INTERNAL_OPERATIONS_PRIVILEGE,
) on OBJECT | FIELD_DEFINITION

type Query @authorize(requires: ACCOUNT_OPERATIONS_PRIVILEGE) {
  users: [User]
  customers: [Customer]
}

type Mutation @authorize(requires: ACCOUNT_OPERATIONS_PRIVILEGE) {
  addUserForCustomer(customerId: Int!, input: AddCustomerUserInput! ): AddCustomerUserResult

  deleteCustomer(customerId: Int! ): String @authorize(requires: SYSTEM_OPERATIONS_PRIVILEGE)
}
```

However, when I attempt to convert our schema to a federated schema, and provide SDL with directives to `buildFederatedSchema`, I get an error like this one:

```shell
api_server/node_modules/graphql/validation/rules/KnownDirectives.js:86
        throw _iteratorError2;
        ^

TypeError: Cannot read property 'kind' of undefined
    at KnownDirectives (api_server/node_modules/graphql/validation/rules/KnownDirectives.js:70:15)
    at api_server/node_modules/graphql/validation/validate.js:63:12
    at Array.map (<anonymous>)
    at Object.validateSDL (api_server/node_modules/graphql/validation/validate.js:62:24)
    at Object.buildSchemaFromSDL (api_server/node_modules/apollo-graphql/src/schema/buildSchemaFromSDL.ts:69:18)
    at buildFederatedSchema (api_server/node_modules/@apollo/federation/src/service/buildFederatedSchema.ts:30:16)
    at Object.<anonymous> (api_server/api/sql/schema.external.js:47:40)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._compile (api_server/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (api_server/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

Support for directives is a roadblock for converting our current GraphQL service into a federated service.

**Comment by trevor-scheer** [comment]
Thanks everyone for all of your suggestions, use cases, and general input - it's much appreciated! Going forward, we plan to support schema directives for **individual services** in the future, but we do not have any plans to add this support at the gateway level.

Though not listed on the issue itself, this work is part of the Apollo Server 3.0 roadmap. Schema construction is undergoing changes as we move away from `graphql-tools`, and custom schema directives will be one of the things that we address at that time.

For those asking about timeframe, I can only speculate that it will be on the order of months. The work for AS3 is a top priority, however we have a lot to accomplish. There _will_ be a time where we would (gladly!) accept and provide guidance for a contribution from the community, but we're not quite there yet. Thanks everyone for your participation and patience - I know this is exciting stuff 😄

**Comment by lethot** [comment]
for those who cannot get directives running at federated service level, you can use mergeSchemas :

```
const federatedSchema = buildFederatedSchema([{
  typeDefs,
  resolvers,
}]);

const schema = mergeSchemas({
  schemas: [federatedSchema],
  schemaDirectives: {
    ...
  }
});

export const server = new ApolloServer({
  schema,
```

**Comment by cosmarc** [comment]
Is [this](https://github.com/apollographql/apollo-server/pull/3464) what are you looking for? It was released with `v2.9.15`.

**Comment by trevor-scheer** [comment]
Closing this, as executable directives are now supported via https://github.com/apollographql/apollo-server/pull/3464 and service-level type system directives are permitted via https://github.com/apollographql/apollo-server/pull/3536.

**Comment by coyotebush** [comment]
https://github.com/apollographql/apollo-server/pull/3736 makes the gateway tolerate usages of type system directives in service schemas. However, federated services still don't return these usages from `_Service.sdl`, as discussed in the first few comments on this issue, so there is no chance for any implementation of a gateway to read them. I think that's because of [this filter](https://github.com/apollographql/apollo-server/blob/945dd297feb818b90d7bde3f77759061a2ce2135/packages/apollo-federation/src/service/printFederatedSchema.ts#L172-L174). Could that filter be removed now that removing it won't break the gateway?

**Comment by sponomarev** [comment]
For all the interested parties: **there is no issue using schema (aka Type System) directives on the federated services** side except the inconvenient API and knotty internals of all the GraphQL tooling.

1. All `printSchema` functions are intended to remove schema directives. [Here](https://github.com/graphql/graphql-js/issues/869#issuecomment-309899380) is the original motivation. Modified `printFederatedSchema` is used exactly to overcome this limitation because Federated Gateway uses federation directives to compose the final schema. So, don't expect to find your directives in SDL.

2. The straightforward approach doesn't work since we provide a ready  `GraphQLSchema` object in `schema: ` argument. [It uses it as-is](https://github.com/apollographql/apollo-server/blob/ce459ce979aacf8f3486804841127d7244646f03/packages/apollo-server-core/src/ApolloServer.ts#L254-L255) and ignores `schemaDirectives: ` completely. 

```js
// That won't enable schema directives
const server = new ApolloServer({
  schema: buildFederatedSchema([{ typeDefs, resolvers }]),
  schemaDirectives,
});
```

So, we should attach them directly to the schema.

Thanks @lethot, he found [a workaround with `mergeSchemas`](https://github.com/apollographql/apollo-feature-requests/issues/145#issuecomment-528430579), but it's still a workaround and it's not idiomatic.

A better and conventional way is to use [`SchemaDirectiveVisitor.visitSchemaDirectives`](https://www.apollographql.com/docs/apollo-server/schema/creating-directives/).

Here is an example:

```js
// That enables schema directives on the federated service side

const schema = buildFederatedSchema([{ typeDefs, resolvers }])

SchemaDirectiveVisitor.visitSchemaDirectives(schema, schemaDirectives);

const server = new ApolloServer({
  schema: schema,
})
```

**Comment by ilmimris** [comment]
Should we add schema directive to every federated schema (service) even if the service does not need the schema directive ?

**Comment by robross0606** [comment]
This still does not appear to be working as per @sponomarev suggestion.  The schema indeed gets modified to show the name of the custom directive.  I can set breakpoints and even see that the custom type instantiated by the `SchemaDirectiveVisitor` is created.  And I can see that the constructor for that custom type is passing up implementations for `serialize`, `parseValue` and `parseLiteral`.  However, none of those functions are ever hit by Apollo when submitting input.  They're completely ignored.

**Comment by sponomarev** [comment]
@ilmimris No, you don't. Schema directives transform types, fields, etc. The affect only the current service.

**Comment by sponomarev** [comment]
@robross0606 Sorry, can't say anything specific without seeing the code you're talking about.

**Comment by robross0606** [comment]
@sponomarev , I'm attempting to tie in the [apollo-server-constraint-directive](https://www.npmjs.com/package/apollo-server-constraint-directive) library to our service which is federated.  The basic steps are as indicated in their README, except instead of calling `makeExecutableSchema()` I'm doing:
```
const { buildFederatedSchema } = require('@apollo/federation')
const { SchemaDirectiveVisitor } = require('graphql-tools')
const federatedSchema = buildFederatedSchema([typeDefsAndResolvers])
SchemaDirectiveVisitor.visitSchemaDirectives(federatedSchema, schemaDirectives)
```
There are no errors from this, and the resulting schema looks for all the world like it should work.  Schema introspection shows the correct types as per the library in places where I've added constraints.  So, for example, if add an `@constraint(minLength: 5)` to a `String!` field, I can see in debug mode that the original type is "wrapped" by the validating type `StringType`:
```
class ConstraintDirective extends SchemaDirectiveVisitor {
  visitInputFieldDefinition(field) {
    this.wrapType(field);
  }

  visitFieldDefinition(field) {
    this.wrapType(field);
  }

  wrapType(field) {
    const fieldName = field.astNode.name.value;
    const type = field.type.ofType || field.type;
    const isNotNull = (field.type instanceof GraphQLNonNull);
    const isScalarOfTypeString = (type === GraphQLString);
    const isScalarOfTypeNumber = (type === GraphQLInt || type === GraphQLFloat);

    if (!isScalarOfTypeString && !isScalarOfTypeNumber) {
      throw new Error(`Not a scalar of type ${type}`);
    }

    if (isScalarOfTypeString) {
      field.type = new StringType(fieldName, type, this.args);
    }

    if (isScalarOfTypeNumber) {
      field.type = new NumberType(fieldName, type, this.args);
    }

    if (isNotNull) {
      field.type = new GraphQLNonNull(field.type);
    }
  }
}
```
The constructor for StringType looks like this:
```
class StringType extends GraphQLScalarType {
  constructor(fieldName, type, args) {
    super({
      name: 'ValidateString',
      serialize(val) {
        const value = type.serialize(val);
        validate(fieldName, args, value);
        return value;
      },
      parseValue(val) {
        const value = type.parseValue(val);
        validate(fieldName, args, value);
        return type.parseValue(value);
      },
      parseLiteral(ast) {
        const value = type.parseLiteral(ast);
        validate(fieldName, args, value);
        return value;
      },
    });
  }
}
```
So, I can see that the correct type is created and "wraps" the original type, and I can see that the GraphQL type in introspection becomes "ValidatedString".  However, making a call to the GraphQL never appears to pass through the `serialize`, `parseValue` or `parseLiteral` functions declared on that `StringType`.

I'm baffled as to why.

**Comment by makaivelli** [comment]
@robross0606 We're also using Federation and faced the same issue when I tried to add validation with `graphql-constraint-directive`. Did you manage to make them work together by any chance?

**Comment by robross0606** [comment]
@makaivelli, I did not end up using `apollo-server-constraint-directive` but _did_ end up using `graphql-constraint-directive`.  That library appears to work a bit differently.  IMO, this is a big problem with Apollo since they keep changing the methodology for doing the same things which causes confusion around these topics.

Here's a simplified example of how I ended up using it:

```Javascript
const { mergeTypeDefs, mergeResolvers } = require('@graphql-tools/merge')
const { constraintDirective, constraintDirectiveTypeDefs } = require('graphql-constraint-directive')

const schemaTypeDefs = require('./schema')
const allResolvers= require('./resolvers')

const directiveTransform = const constraintDirective()]
const directiveTypeDef =  schemaDef: gql`${constraintDirectiveTypeDefs}`

const allTypeDefs = mergeTypeDefs([{ schemaDefs: directiveTypeDef  }, schemaTypeDefs], { all: true })

const typeDefsAndResolvers = {
  typeDefs: allTypeDefs,
  resolvers: allResolvers
}

let federatedSchema = buildFederatedSchema([typeDefsAndResolvers])
  federatedSchema = directiveTransform(federatedSchema)
}

module.exports = {
  federatedSchema,
  schemaDirectives
}
```

**Comment by sbilello** [comment]
Is there a way to integrate the https://github.com/teamplanes/graphql-rate-limit at apollo/gateway level?
