### ISSUE TITLE
Allow to provide custom ObjectCache for InMemoryCache 

### ISSUE THREAD

**Issue by morrys** [apollographql/apollo-feature-requests#154]
Hi all,
I wanted to ask if it was possible to add customData to the parameters provided by InMemoryCacheConfig. This to best integrate the library https://www.npmjs.com/package/@wora/apollo-cache

I think it is a valid alternative to apollo-cache-persist and your opinion is welcome.

Thank you,
Lorenzo

**Comment by wtrocki** [comment]
Any reason why this cannot be done in apollo-cache-persist?
Apollo-Cache-Persist library is fully supported by the community and we are really looking for feedback on how this library can move forward to support more advanced cases like filtering etc.

**Comment by morrys** [comment]
I opened this issue to evaluate with the people who maintain apollo projects what is the best way to evolve these features and how to evolve the `@wora/cache-persist` library that I use as persistence in other contexts.

**Comment by wtrocki** [comment]
I would personally love to see PR to the apollo-client repository so I can help you with these goals and comment on the code. Apollo client 3.0 will come with cache invalidation feature that may change some internal implementations. It is nice to drop some potentially breaking changes now for the community to comment on. Lack of cache persistence in InMemoryCache was an always big problem. 

> I think it is a valid alternative to apollo-cache-persist and your opinion is welcome.

I personally would love to move collaboration on this package rather than creating alternatives. This is where the most community is now and there are couple issues that we can resolve to make it nice. Apollo-Cache-Persist can be used now to achieve offline capabilities for queries.

**Comment by jerelmiller** [comment]
Hey all 👋. As @benjamn mentioned in [this comment](https://github.com/apollographql/apollo-client/pull/5601#issuecomment-709524488) try using `apollo3-cache-persist` which works with AC3.

I'm doing a bit of housekeeping to try and cleanup some older PRs and issues. Since we've closed #5601, I'm going to close this issue as well. Feel free to re-open the issue or create a new discussion if need be. Thanks!
