### ISSUE TITLE
cache-only fetch policy should work with refetch

### ISSUE THREAD

**Issue by toddtarsi** [apollographql/apollo-feature-requests#197]
Okay, so when dealing with an async application and doing store resets and all of that stuff, sometimes a cache-only query just runs before the store is hydrated adequately.

In those instances, it can be nice to go

```
props: (data, ownProps) => {
  if (data.result) return { foo: 'bar' };
  return { refetch: data.refetch };
},
```

And then check somewhere downstream like:

```
componentDidUpdate() {
  if (!foo) return this.props.refetch();
}
```

However, this doesn't work because refetch doesn't work with the cache-only fetch policy, so instead I have to rig up my own observable that pumps manual readQuery checks to see if its there and then mount the query component. It seems a little stupid to me that I can't just re-run the query with refetch even if it is client side.

I'm not sure how this would exactly be implemented, but I suspect it wouldn't be difficult and is more configurational than anything.

My solution is better because it makes things more consistent and allows for people to refetch client side queries in instances when there was no result to watch and the observable is just stuck on empty.

**Comment by jerelmiller** [comment]
Hey @toddtarsi 👋 

I know this issue is a bit old now. I'm curious if any modern version of Apollo Client addresses your request here? `refetch` _should_ now guarantee a network request, even if your `fetchPolicy` is a cache specific policy.

This being the case, I'm going to go ahead and close this issue. Feel free to ping us if modern versions of the client don't adequately address what you're looking for, or feel free to file a bug report in the [apollo-client repo](https://github.com/apollographql/apollo-client). Thanks!
