### ISSUE TITLE
V3 Client - Allow FieldPolicy return values to be persisted back to cache

### ISSUE THREAD

**Issue by ahrnee** [apollographql/apollo-feature-requests#201]
**THE CONTEXT**
There are a number of cases where client-only graphql fields contain data that is dependent upon sibling or child fields. One example is when client-only fields are used to contain client-side optimization data (such as normalization data). 

**THE NEED**
When the sibling and child data changes, the dependent @client data needs a to be updated

**THE OPTIONS**
The two options to achieve this seem to be:

1. When the dependent data changes, clear/invalidate the client-only field, and allow it to regenerate the next time the field is requested, and (crucially) allow it to be persisted back to cache, so that it does not have to be regenerated on every request

2. Add logic to every mutation of sibling and child fields to update the client-only field with regenerated data

Option 1 is, in my case, more more preferable. It allows the logic for the field generation and maintenance to be encapsulated in one place. Conversely, option 2 requires every single mutation on sibling or child dependencies to have have knowledge of this field, how to generate it, and to create and maintain code to do so. It creates a very leaky abstraction.

**THE PROBLEM**
Option 2 is not optimal, and there is currently no good way to achieve option 1. The things that have been tried (and failed):

1. Leverage Client Resolvers with @client(always:true) fields
This _almost_ works - BUT the client resolvers are not triggered data updates received through the observableQuery stream

2. Leverage FieldPolicies
Field policies seem to be triggered, even on data updates received through the observableQuery stream BUT they don't seem to have access to the apolloClient or client cache. As such, there is not the opportunity to persist the updated field back to cache (so that it does not have to be generated on every request)

**SUGGESTED SOLUTION**
Either:
1. Provide Client Resolvers the opportunity to interact with data from watched (Observable) Queries

OR

2. Provide FieldPolicies access to the cache object, so that values can be persisted back to cache

**Comment by benjamn** [comment]
This might already be possible!

To solve the general problem of allowing `read` function results to be cached, there's an `options.storage` object that you can use to persist data:
```ts
const cache = new InMemoryCache({
  typePolicies: {
    SomeType: {
      someField(existing, { args, storage }) {
        if (existing) return existing;
        if (storage.cachedValue) return storage.cachedValue;
        return storage.cachedValue = computeSomeExpensiveValue(args);
      },
    },
  },
});
```
The `options.storage` object is private and unique to the `someField` field of this particular `SomeField` object. If you have a `keyArgs: [...]` configuration for `someField`, there will be a unique `options.storage` object for each combination of the key arguments. By default, whenever you have a `read` function, `keyArgs: false` is assumed unless otherwise specified, so you don't usually have to think about this point.

You can put whatever you want into `options.storage`, using whatever keys you like. For example, if `args.id` is the ID of the object that will be returned, you might want to use `options.storage[args.id]` instead of just `options.storage.cachedValue`, so that you can store separate cached values for each `args.id`.

The `options.storage` object exists as a layer on top of the actual `EntityStore`, so any actual data written into the cache for this field will be provided by the `existing` parameter to the `read` function, and these `options.storage` objects will not be persisted along with actual cache data when you call `cache.extract()`.

You definitely could write to the actual cache while reading from it, but that's a lot more tricky/expensive than using `options.storage` to cache expensive field results.
