### ISSUE TITLE
[v3] Allow "no cache" and "custom fetch" to enable running in NodeJS

### ISSUE THREAD

**Issue by 0xAsimetriq** [apollographql/apollo-feature-requests#228]
I was looking for a graphql client I could use server-side to query other graphql api's and came across this [stackoverflow question](https://stackoverflow.com/questions/40792344/does-apollo-client-work-on-node-js) which explains how to do it with apollo v2.

I tried this with current beta of v3 and it seems cache is required there, and there is no option to add custom `fetch`. Were these changes intentional for v3 or should they be considered to allow using client in NodeJS environment?

**Comment by jerelmiller** [comment]
Hey @0xAsimetriq 👋 

I know this issue is a bit dated now, but I'm curious if the `HttpLink` [custom fetch](https://www.apollographql.com/docs/react/api/link/apollo-link-http#customizing-fetch) option solves what you're looking for. Perhaps this wasn't available at the time you were trying v3?

I'm going to go ahead and close this issue as completed, but feel free to ping us if this doesn't address what you're looking for!
