### ISSUE TITLE
Add component re-render on change to reactive variable 

### ISSUE THREAD

**Issue by dvakatsiienko** [apollographql/apollo-feature-requests#244]
# Description

Reactive variables are great!
But it is very desirable to have re-render on reactive variable change.
My use case is pagination: i store pagination object inside of a reactive var:

```graphql
input PaginationInput {
    orderBy: [OrderCriteria]
    limit: Int
    offset: Int
}
```

Storing pagination state in reactive variable allows to persist that between route transition.
But the problem is that when pagination state is changed it does not trigger component re-render which makes that impossible to accomplish such kind of functionality.
This is why a feature like that would be a tremendous addition!

**Comment by kosanna** [comment]
I have a few similar use cases when I am attempting to use reactive variables solely for ui state transitions, aka keeping the state wether if modal is open or closed. I am able to set and unset them correctly based on the client actions/button clicks, however it does not trigger components to update to use the new values in the variables. If anyone has any sort of a workaround in the meantime how to achieve it in a nice way with useEffect or similar I would highly appreciate it being shared. 
At the moment I'm quite inclined to just use good old redux in favour of Apollo state management otherwise... or possibly could use writeQuery...but it's so much more boilerplate that reactive variables.
