### ISSUE TITLE
Support BSON / EJSON format

### ISSUE THREAD

**Issue by dobesv** [apollographql/apollo-feature-requests#267]
It would be great to support BSON / EJSON for communications because this is able to preserve additional types of values, like date, buffer, and integer.

The project(s) wouldn't necessarily have to support this natively.  Just add options for `stringify` and `parse` to the client and server libraries and let people pass in whatever implementation they want to use.

**Comment by trevor-scheer** [comment]
I'm inclined to say this isn't a request I'm interested in entertaining for Apollo Server, mostly on the grounds that I've never heard demand for it. Since your comment in 2020, there's been a lot of work to standardize [GraphQL over HTTP](https://github.com/graphql/graphql-over-http). The spec _does_ permit other serialization formats, but JSON is the standard. Apollo Server is also particular about the `content-type` used w.r.t. CSRF prevention, so that would be an additional detail to consider.

I'm open to reconsidering my stance, but I'd first like to see a good use case and some real desire for this followed by a PR or PoC. If this is still interesting to you, please feel free to open an issue in the Apollo Server repo.

**Comment by dobesv** [comment]
Would you consider adding an option to pass a custom stringify / parse function into apollo server, rather than implement any specific alternative format ?

**Comment by trevor-scheer** [comment]
I'll be super clear just to set the right expectation: I don't think this is a good idea and I would prefer not to add the configuration points you're suggesting. This isn't work I will take on myself.

My biggest concern is that decoupling from `JSON.*` may not be as simple as it sounds and that it will add complexity or require a non-trivial amount of refactoring. If that turns out to not be the case I'll be much more amenable to this change.

You are welcome to open a PR if you feel strongly about this, and I'll consider it if:
* there's a good argument for this addition (what are you trying to accomplish that you can't with JSON, provide examples)
* ideally I'd like to see additional interest, but I won't block you on that alone
* new tests and updates to documentation
* no breaking changes
* this doesn't add a significant amount of complexity (i.e. if decoupling from `JSON.*` turns into much of a refactor, I'm not really interested in adopting this change)

I don't mean to sound harsh, but I do want to give you pause. I want to respect your time and I won't feel great about you doing work on this and then having me scrap it. Also note that I'm only speaking for the Apollo _Server_ project.

**Comment by dobesv** [comment]
I see, thanks.  As you've said this hasn't gained a lot of attention in the last few years, probably not worth it.  We have workarounds for sending custom scalars in JSON so this isn't critical, just a "would be nice".  Kind of strange GraphQL still has no built-in Date support after all these years, but that's a whole other discussion!
