### ISSUE TITLE
Add an option to configure result caches max size

### ISSUE THREAD

**Issue by sofianhn** [apollographql/apollo-feature-requests#289]
The memoization caches used in [maybeBroadcashtWatch](https://github.com/SofianHn/apollo-client/blob/main/src/cache/inmemory/inMemoryCache.ts#L371), [executeSelectionSet](https://github.com/SofianHn/apollo-client/blob/main/src/cache/inmemory/readFromStore.ts#L156) and in [executeSubSelectedArray](https://github.com/SofianHn/apollo-client/blob/main/src/cache/inmemory/readFromStore.ts#L343) uses the default max size in optimism of [Math.pow(2, 16)](https://github.com/benjamn/optimism/blob/main/src/index.ts#L91).

Those caches will grow based on application usage and in the case of [executeSelectionSet](https://github.com/SofianHn/apollo-client/blob/main/src/cache/inmemory/readFromStore.ts#L156) and [executeSubSelectedArray](https://github.com/SofianHn/apollo-client/blob/main/src/cache/inmemory/readFromStore.ts#L343) they will continue to grow until the cache limit is reached since they don't offer a "cleaning mechanism", unlike `maybeBroadcastWatch`, which [explicitly removes](https://github.com/SofianHn/apollo-client/blob/main/src/cache/inmemory/inMemoryCache.ts#L225) cache entries.

**Proposal**

Add an optional `resultCachMaxSize` configuration option to customize the max size and reduce the potential max memory impact while retaining the performance benefit of `resultCaching`.

`
const cache = new InMemoryCache({
    resultCachMaxSize: 5000
});
`

Here is [the proposed change + tests](https://github.com/SofianHn/apollo-client/commit/be42d88ce131d5dffea01a92785f41580fa0a806).

**Comment by SofianHn** [comment]
I am also exploring what it takes for `executeSelectionSet` and `executeSubSelectedArray` to clean up cache entries based on upstream signals of eviction/gc. I got a prototype working, but not %100 there test-wise. It will be great to know if this the right direction.

**Comment by brainkim** [comment]
Thanks for opening this issue! This was actually something I was exploring while doing some related bug fixing. Is there a specific motivation for why the default cache sizes are too large? I’m very curious to know what your use-case for this is, and if it’s performance-related or whatever.

**Comment by SofianHn** [comment]
Thanks @brainkim for the quick response.

My use case is actually memory. For a product that runs for multiple days, we expect users to get fresh content continuously. We started noticing that the caches for `executeSelectionSet` and `executeSubSelectedArray` can grow to account for large retained memory. My first impression is that we could have been doing something wrong. Still, upon debugging, I did not find anything out of the ordinary. We missed some `KeyArgs` field policies that improved re-computation, but more entries are added whenever you get fresh content (essentially queries with new keys). That is how we arrived to reconfigure the cache limit to retain `resultCaching` with a smaller memory footprint as a compromise.

As I mentioned in my first comment, in a perfect world I would love for this to be "related" to eviction. We can reason about what objects to keep in cache and we might be able to tie those to the cahce entries and remove them upon eviction. Not sure if this is something you considered as well but I can share my prototype if you are interested.


Reading your [comment](https://github.com/apollographql/apollo-client/issues/7436#issuecomment-821243699), I also just learned about [4141](https://github.com/apollographql/apollo-client/issues/4141#issuecomment-733091694), seems promising. I will look into that as well to see if it can help us. Funny enough, we were unable to move to 3.4 due to some memory leaks but I will give that a second look.

**Comment by SofianHn** [comment]
Here is the [prototype](https://github.com/SofianHn/apollo-client/commit/3f8536d8ae248624411fb7b6d4a4f06642c2a88b) for the automatic removal of entries based on eviction. I verified it in a test app and in a unit test. It does the intended behavior for my use-case.

It will require a minor [addition](https://github.com/SofianHn/apollo-client/commit/9e20661bb8095a669fe9e6c4033c4dbd3bed9b9b) to the optimism API. Happy to discuss in more detail if this is a direction you want to consider.

**Comment by brainkim** [comment]
@SofianHn You may be interested in the following issue https://github.com/apollographql/apollo-client/issues/7942. Personally, I’m very eager to get this kind of issue sorted, and connecting the `cache.evict()` API to the optimism caches is probably a good idea. If you open a PR on apollo-client/optimism and ping me I’ll try to cut through any red tape to get it seen!

**Comment by SofianHn** [comment]
Hey @brainkim, have you had a chance to look at the PR? Any feedback?

**Comment by brainkim** [comment]
@SofianHn I pinged @benjamn on slack and I think he has some feedback about the optimism stuff. It’s his library and the code is comfy there so I don’t want to be too insistent. If you want to open a PR against Apollo client with the changes you want (not sure how testing that would work) I’m happy to start the review process there. This is actually something I would want to sneak into 3.4 but that’s up to @benjamn of course.

**Comment by SofianHn** [comment]
Thanks, @brainkim I can open a draft PR against Apollo but that PR will depend on the upstream from Optimism (at least the current approach). I will include a patched package to help get this review started.

If there is any specific concern from @benjamn that I can help with, happy to address them as well.

**Comment by SofianHn** [comment]
@brainkim, PR added: https://github.com/apollographql/apollo-client/pull/8107

**Comment by benjamn** [comment]
This was implemented and released in `@apollo/client@3.4.0-beta.24`, thanks to @sofianhn's PR https://github.com/apollographql/apollo-client/pull/8107. 🎉
