### ISSUE TITLE
Apollo Client for Flutter

### ISSUE THREAD

**Issue by daniarmas** [apollographql/apollo-feature-requests#290]
Currently Apollo doesn't offer an official Flutter Client  for developers using [Flutter ](https://flutter.dev/)as their mobile Development framework

**Comment by medz** [comment]
Apollo GraphQL launches Flutter client is a very good choice, the current third-party GraphQL implementation on pub.dev is very bad!

**Comment by medz** [comment]
> https://pub.dev/packages/graphql_flutter

Implementation is not good

**Comment by jpvajda** [comment]
Just adding that I had a chat this week with a current Apollo Server user that expressed interest in a better Flutter GraphQL Client than what is currently available, as they use flutter for their mobile apps.

**Comment by jpvajda** [comment]
For Flutter Developers looking for a Codegen solution for Dart, this was recommended by an Apollo User. 

https://github.com/heftapp/graphql_codegen

**Comment by megamaddu** [comment]
@medz not good how? Starting to look into this as well so I'm curious how you'd compare the three existing options. Plus that feedback might help direct future work whether or not it's from Apollo.

**Comment by medz** [comment]
> @medz not good how? Starting to look into this as well so I'm curious how you'd compare the three existing options. Plus that feedback might help direct future work whether or not it's from Apollo.

It's been a long time since my last reply. These two packages have developed well during this time. But other packages than `ferry` have a rough implementation!

Let me put it another way, the current front-end GraphQL client is not the best implementation. Still at the stage of writing SDL.

Maybe I won't use any GraphQL front-end packages anymore because I've switched to gRPC. Using protobuffer for gRPC makes it a lot of fun for me to work with backend APIs on post development.

Perhaps what is missing from the front end is a toolkit with CRUD or generating services from GraphQL SDL, although I have plans to make it, but I'm not sure if I want to develop it. Because I've tried my best not to use GraphQL, which makes back-end development a joy, but using it on the front-end is a pain for our app and web developers.

> The above is just my personal opinion, if you don't like it, don't spray it.

**Comment by megamaddu** [comment]
Thanks!

I'm curious what you're referring to here:

> current front-end GraphQL client is not the best implementation. Still at the stage of writing SDL.

**Comment by medz** [comment]
> @megamaddu  I'm curious what you're referring to here:
> 
> > current front-end GraphQL client is not the best implementation. Still at the stage of writing SDL.

Write a .graphql query statement file with no type guidance and no security testing, mainly when the server has developed a complete GraphQL SDL (schema.graphql) for the client, and most clients need to follow the `schema.graphql ` Write your own query and generate code.

Perhaps this is how the query is written for the minimal query implementation, but it's not type-safe. Because developers still write the wrong query by mistake.

I have an idea, why not use `schema.graphql` to generate a builders and then generate SDL with the parameters passed by the developer to send to the server? You only need to reverse the steps of using GraphQL on the current front end to achieve type-safe, query-robust SDL.

I have been thinking about this idea for a long time, maybe I will try it in the near future (CRUD inspiration from Prisma ORM)

> Also, as a front-end developer, I hate writing SDL and then generating code.
> In back-end development, we have first-code. In fact, the front-end really hopes to have this feature, at least to make it less painful for us front-end developers to use GraphQL.

**Comment by jpvajda** [comment]
Just adding  a reference to the growing interest in Flutter for Android Development,[ DroidCon London](https://london.droidcon.com/agenda/) had 9 talks on Flutter.

**Comment by marc-wilson** [comment]
+1

**Comment by mariapapag** [comment]
Really having a hard time finding a work around to be able to use GQL subscriptions in a flutter app. Please advise

**Comment by mayank-ast** [comment]
+1

**Comment by mayank-ast** [comment]
+1

**Comment by geminiyellow** [comment]
is there any good news？

**Comment by marc-wilson** [comment]
> is there any good news？

Also curious on the state of this request. Is there any official response from the apollo team? Even if it's "it's on the roadmap" it would be nice to get some form of acknowledgement.

**Comment by jerelmiller** [comment]
Hey all 👋 

Thanks for the nudge and thanks for your patience! Unfortunately this is not something we are planning to do in the foreseeable future as we just don't have the bandwidth to support a Flutter client at this time. As such I'm going to close the issue. Sorry this isn't better news!
