### ISSUE TITLE
Pass subscription parameters through to the Subscription Resolver

### ISSUE THREAD

**Issue by serle** [apollographql/apollo-feature-requests#30]
I have the need to be able to set the channel name dynamically based on the subscription parameters / variables. Currently the subscription resolver looks like

`subscribe: () => pubsub.asyncIterator(<calculated_channel_id >)`

I would like the method signature to be alligned more with other resolvers, but at least provide access to the context and variables:

`subscribe: (variables, ctx) => pubsub.asyncIterator( function(variables, ctx) )`

This Feature Request should not change the current behavior for subscription resolvers that use hard-coded channel names.

**Comment by mihajlon97** [comment]
That solution works now 
See [this]( https://github.com/apollographql/apollo-server/issues/1385)

**Comment by jerelmiller** [comment]
Hey there 👋 

We've migrated this repo to be an Apollo Client only request repo. Given [this comment](https://github.com/apollographql/apollo-feature-requests/issues/30#issuecomment-463991240), this issue seems to be resolved. If you need any additional assistance with Apollo Server feature requests, open those requests directly in the [Apollo Server](https://github.com/apollographql/apollo-server) repo. Thanks!
