### ISSUE TITLE
`Query.apollo` returns subfields of information about the Apollo Platform.

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-feature-requests#328]
What if a user could query `Apollo`  and return all the version IDs of the client, server, router, etc of what they are using? 
We could add a `Query.apollo` field, with various `subfields` for any number of informational queries that relate to different parts of the Apollo Platform. 

```js
query ApolloVersions {
  apollo {
    client { version }
    server { version }
    federation { version }
    router { version }
  }
}
```

When the query is executed:

- Apollo Client returns version information
- Apollo Server returns version information
- Apollo Router returns version information
- Apollo Federation returns version information

**Comment by jpvajda** [comment]
@benjamn 👋

**Comment by trevor-scheer** [comment]
Not sure if this was meant to be something that Apollo's graph should offer or that people using Apollo Server should get for free, but in either case I don't think there's been any demand for it.
* If intended for our graph, package versions are all readily available information through the web and CLI tooling. I don't see much reason for users to want to send a query to our API to derive that info rather than straight from the respective package repositories.
* If intended for subgraphs, this can be done in userland trivially and I'm not sure how useful it would really be, so I'd hesitate to make that part of the Apollo Server / Gateway / Router offering even as an enabled feature.
