### ISSUE TITLE
graphq visualisation for studio

### ISSUE THREAD

**Issue by macrozone** [apollographql/apollo-feature-requests#337]
For talking about a graph, modelling it, reviewing it and understanding it, its often useful to have a more visual representation.

I did some research and found this one which works quite good: https://github.com/IvanGoncharov/graphql-voyager

as mentioned in https://github.com/IvanGoncharov/graphql-voyager/issues/187#issuecomment-1191534447

I think apollo studio could and should include something like that which would be a great addition to the schema inspector. 

I believe it would be even safe-enough and easy to even include graphql-voyager directly in studio, maybe as a tab here:

<img width="612" alt="Bildschirmfoto 2022-07-21 um 16 08 12" src="https://user-images.githubusercontent.com/1972353/180249341-8e212569-bffb-4d0e-93d5-f9b807a90ad7.png">

**Comment by FluorescentHallucinogen** [comment]
+1 for the idea of integrating GraphQL Voyager into Apollo Studio. 👍

GraphQL Voyager could be used not only for visualizing GraphQL schema in the "Schema" tab, but e.g. for visualizing diff between two GraphQL schemas in the "Changelog" tab (see https://github.com/kamilkisiela/graphql-inspector/pull/1746).

Also GraphQL Voyager can be used for visualizing heatmap (which resolvers are triggered by GraphQL operations, see https://github.com/IvanGoncharov/graphql-coverage/blob/master/demo.gif) and for visualizing error rates for GraphQL types and fields.

**Comment by FluorescentHallucinogen** [comment]
@daniman PTAL. :wink:

**Comment by daniman** [comment]
@FluorescentHallucinogen I like the idea. The reason we haven't brought Voyager into Studio in the past is that it gets unusable fairly quickly for large schemas, and when we introduce features, they need to work for all our users. We've considered layering something like Voyager with filters to help with that problem. Working on schema visualization is on our roadmap for Studio. Hopefully we'll be able to get to it sooner rather than later.

**Comment by KennyHammerlund** [comment]
+1 for the implementation of voyager with Studio
@daniman I agree that large schemas are hard to deal with on a single canvas. Maybe this could be implemented at the subgraph level similar to how subgraph schema can be shown in the Schema=> SDL tab. 

@FluorescentHallucinogen cool idea integrating the heat map based on traffic. I think the reverse would be helpful too. I.e. the darker the blue the longer it has been since last used. That would help with deprecation.

**Comment by jerelmiller** [comment]
Hey @macrozone 👋 

We have shifted this repo to be specific to the [Apollo TypeScript Client](https://github.com/apollographql/apollo-client). As such, I'm going to go ahead and close this issue.

If you're still in need of assistance or would like to raise this request again, please open an issue in the [Apollo Studio Community repo](https://github.com/apollographql/apollo-studio-community). Thanks!
