### ISSUE TITLE
Support for HotChocolate Batching

### ISSUE THREAD

**Issue by erwan-joly** [apollographql/apollo-feature-requests#387]
Hi, recently there was quite a big change on HotChocolate (One of the main c# graphql server library) on how to handle graphql batching. 
cf https://chillicream.com/docs/hotchocolate/v13/server/batching and https://chillicream.com/docs/hotchocolate/v13/migrating/migrate-from-12-to-13#batching

Sadly it does not work anymore with apollo-link-batch-http https://www.apollographql.com/docs/react/api/link/apollo-link-batch-http/

I think their is no change/minimal change on the behavior for the request sent to the server. 
The response format however require changes as it is not an array anymore but a multipart response which is useful for streaming the results.

**Comment by alessbell** [comment]
Hi @erwan-joly 👋 Very interesting! Thanks for opening this issue, I'll take a look and should have a snapshot release for you to try out tomorrow. Cheers!

**Comment by alessbell** [comment]
@erwan-joly I've opened a draft PR (linked on this issue). You can test it out via `npm i @apollo/client@0.0.0-pr-10830-20230502215140` - would love any feedback on how it works with the Hot Chocolate server you're running, thanks!

**Comment by erwan-joly** [comment]
will test this today thanks!

**Comment by erwan-joly** [comment]
@alessbell it does not seems to work.
Here what I could discover:
- It seems like the payload is missing all the variables properties (those are empty even when having it set in the useQuery)
- Error message is : Server returned results with length 1, expected length of 11
I think this is link to the previous error not having the variables.
- Response only continue streaming until the first errors (that's from hotchocolate, not sure it's normal as it sounds weird to fail the whole batch request if only one item is failing)

**Comment by alessbell** [comment]
@erwan-joly thanks for trying it out and passing along that feedback!

> It seems like the payload is missing all the variables properties (those are empty even when having it set in the useQuery)

Can you elaborate a bit more here? It sounds like you're referring to the variables sent with the request which are missing. I'm asking because I haven't modified the part of the link that generates the request, only how the response is parsed.

I'll take a look as soon as I can, but if you have a simple runnable HotChocolate server repo you could share it would definitely help speed up my debugging. Thanks!

**Comment by erwan-joly** [comment]
https://github.com/erwan-joly/BatchPoc/tree/master

for api : 
you'll need the latest dotnet version install (sdk and runtime) https://dotnet.microsoft.com/en-us/download/dotnet/7.0
go to api/api 
`dotnet build` 
`dotnet run` to start the API

for the frontend repro in spa
go to spa
`npm i`
`npm run dev`

**Comment by alessbell** [comment]
Thanks for this reproduction, @erwan-joly! I have a few things on my plate atm but should be able to take a look in the next week or so, thanks for your patience :)

**Comment by erwan-joly** [comment]
@alessbell any update ? let me know if you need help running the reproduction

**Comment by alessbell** [comment]
Hi @erwan-joly 👋 Thanks so much for your patience on this one!

I was able to run your demo HotChocolate app, it was extremely helpful. The issue with variables being removed from the request was actually an unreleased bug in `BatchHttpLink` on our `release-3.8` branch, created during a refactor to support the `includeUnusedVariables` option. We would have missed that if not for this feature request!

Once I fixed that, I saw the issue. HotChocolate's batching over multipart HTTP returns a payload like this:

```

---
Content-Type: application/json; charset=utf-8

{"data":{"number":123}}
---
Content-Type: application/json; charset=utf-8

{"data":{"number":500}}
-----
```

### Apollo Client's `readMultipartBody` was designed for `@defer`/`@stream`

> Feel free to skip this section if you're up-to-date on the `@defer`/`@stream` spec proposal ⏩

Apollo Client's multipart response handling in [`readMultipartBody`](https://github.com/apollographql/apollo-client/blob/a1dac639839ffc5c2de332db2ee4b29bb0723815/src/link/http/parseAndCheckHttpResponse.ts#L18) could more accurately be named `readDeferStreamMultipartBody` since it was implemented for use in `HttpLink` in order to support the `@defer` (and later `@stream` and `@live`) directives.

It implements the latest `@defer`/`@stream` spec proposal and _doesn't_ support reading chunked responses that contain arbitrary/non-spec proposal compliant JSON (in this case, only a `data` key, whereas `@defer`/`@stream` payloads contain `incremental` and `hasNext` keys, for example).

### Multipart batched requests

Since Apollo Client's utilities for reading multipart responses were designed for a different use case, they aren't compatible with HotChocolate's batching over multipart HTTP.

It's important to say that the protocol for `@defer`/`@stream` does not make sense in the context of batched requests, since we're not dealing with `incremental` chunks that accumulate/are applied at different "paths". So the question becomes: should compatibility with a HotChocolate batching feature be built into `BatchHttpLink`?

### Using a custom link

Right now, I think a **custom link implementation** is the better choice. If using multipart over HTTP eventually becomes the standard transfer protocol for batched requests, we could eventually merge it into our `BatchHttpLink`, but we have no plans to do so in the near future.

The HotChocolate docs suggest using `meros` for parsing its multipart responses, so I've created a custom link that does this in a fork of your repo: https://github.com/erwan-joly/BatchPoc/pull/1. I'll add some explanatory comments around a few details on the PR itself in case you move forward with it.

For now, I'll close out this request since we don't have plans to include this in core at the moment, but thanks for raising this request!
