### ISSUE TITLE
Remove "React" from the docs and keep it generic

### ISSUE THREAD

**Issue by martinszeltins** [apollographql/apollo-feature-requests#408]
When reading the docs, it gives an impression that Apollo Client is a React library because it says in the menu `Client (React)` and later it says

> This documentation set focuses on React, but Apollo Client supports many other libraries and languages: Angular, Vue ...

https://www.apollographql.com/docs/

Developers are trying to find documentation that is not framework specific and cannot find it.

How about removing the `React` part and just keeping it a generic JavaScript library so that people who use other frameworks do not feel sidelined.

**Comment by jerelmiller** [comment]
Hey @martinszeltins 👋 

You're correct in that we should have more of an emphasis on some of the core client API and not so focused on React. This is on our radar and a change we do plan to make to our docs, though I can't guarantee a timeline when we will be able to get this completed as its a pretty big undertaking.

> How about removing the `React` part and just keeping it a generic JavaScript library so that people who use other frameworks do not feel sidelined.

As for this request, we likely won't remove `React` entirely since it is the only 1st party library we currently have bindings for. The others (Vue, Angular, etc.) are all 3rd party maintained, so we will still likely have an emphasis here. `React` likely just won't be the viewpoint which the entire set of docs are written and will instead be replaced by some of the core APIs.

We've got https://github.com/apollographql/apollo-client/issues/9607 open currently that we will track this work in, so I'm going to go ahead and close this as a duplicate. Just wanted to at least let you know that we are planning on this at some point in the future!
