### ISSUE TITLE
Documentation for v1

### ISSUE THREAD

**Issue by jimrandomh** [apollographql/apollo-feature-requests#50]
Continuing issue https://github.com/apollographql/apollo-client/issues/2505 which was closed since it should be in apollo-feature-requests.

There does not seem to be an online copy of the Apollo documentation for v1.x. There is a partial copy at https://s3.amazonaws.com/apollo-docs-1.x/index.html but its internal links and search link into the v2 docs, so it isn't usable.

This is a problem for people who can't migrate to v2.x, and also for migrations themselves. In my case, I'm trying to figure out some code in Vulcan that is using query reducers, and the available documentation only says that the API has been removed and replaced with something more general. This doesn't help me with understanding the old behavior.

**Comment by fbartho** [comment]
If you want, you can go read the documentation-markdown files at the git-tag for the release you are working with?

**Comment by reverie** [comment]
It would be great to see this. Check out how Django does it, there are buttons on the bottom-right that tell you which version you're on and make it easy to switch: https://docs.djangoproject.com/en/2.1/

It doesn't have to go that far, but it's needlessly difficult to work on an older project when you don't know which of the docs available online apply to your version.

**Comment by ballenwillis** [comment]
This hasn't gotten any attention in a while which is worrying. Finding docs has been a massive PITA since apollo upgraded to v2 and my team (including me) doesn't like that we're now required to use the `Query` and `Mutation` components instead of `graphql` from `react-apollo`. 

We don't have time to run this upgrade on our entire codebase anytime soon, and we don't see any benefit of doing so. We don't need any of the new features Apollo v2 has to offer, and we're still going to use v1. The literal only pain point of using v1 is the fact that we struggle to find documentation, and it's very frustrating.

All that negativity being said, I do want to thank the Apollo team and other contributors for your hard work. Other than this documentation issue, I've had a very pleasant experience using Apollo.

**Comment by jerelmiller** [comment]
Hey all 👋 

At this point, v1 is quite old and we have no intention of bringing back the docs. Since this issue is quite old at this point, we are going to go ahead and close this. Thanks!
