### ISSUE TITLE
Is there a way/ project that would make apollo-client queries return Immutable.js structure?

### ISSUE THREAD

**Issue by jalchr** [apollographql/apollo-feature-requests#56]
Migrated from: apollographql/apollo-client#2597

**Comment by benjamn** [comment]
Our vision for the future of Apollo Client caching is that cache results should be immutable, because that assumption unlocks significant optimizations for most UI rendering frameworks. However, we have not seen a need to return fancy persistent data structures. A deeply frozen (in development) tree of normal JS objects has all the benefits of immutable data structures.
