### ISSUE TITLE
graphql-anywhere/filter should have an option to preserve __typename

### ISSUE THREAD

**Issue by smeijer** [apollographql/apollo-feature-requests#71]
When using the `mutation` `update` method, or passing data to `update` via `optimisticResponse`, it's nice to use `filter` for creating the correct datastructure. Unfortunaltely, `filter` strips away `__typename` as well. Thereby, causing errors like: `Missing field __typename in ...`.

It would be nice if `filter` would have a third argument, that could be set to preserve the `__typename`s.

```js
import { filter } from 'graphql-anywhere';

const todo = filter(TODO_FRAGMENT, data);
// todo { _id: 'foo', title: 'bar' }

const other = filter(TODO_FRAGMENT, data, { typename: true });
// other { _id: 'foo', title: 'bar', __typename: 'Todo' }
```

More concrete example:

```js
import { graphql } from 'react-apollo';
import { filter } from 'graphql-anywhere';

const withAddTodo = graphql(ADD_TODO_MUTATION, {
  options: {
    update: (store, { data: { addTodo } }) => {
      const todo = filter(TODO_FRAGMENT, addTodo);

      const query = { query: LIST_QUERY, variables: { _id: addTodo.listId } };
      const data = store.readQuery(query);

      data.list.todos.push(todo);
      store.writeQuery({ ...query, data }); // err `Missing field __typename in ...`
```

**Comment by jerelmiller** [comment]
Hey @smeijer 👋 

I know this issue is a bit old by now. `graphql-anywhere` has been [deprecated](https://www.npmjs.com/package/graphql-anywhere) and is no longer maintained. I'm going to go ahead and close this feature request. Feel free to additional to open an additional request if you'd like to propose ideas for more modern versions of Apollo Client. Thanks!
